from .not_found_404 import not_found_404
from .acceuil import page_acceuil
from .parametres import page_parametres
from .a_propos import page_a_propos
from .notifications import page_notifications
from .sauvegardes import page_sauvegardes
from .systemes import page_systemes
from .visualisation import page_visualisation
from .non_autorise import page_non_autorisee